### ISSUE TITLE
Добавить страницу администрирования учетных записей студентов

### ISSUE THREAD

**Issue by BikeInventor** [KirillMaster/web-test#106]
![uploads/ab75cd67-5797-4421-a09c-f962c8e4a64c/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fab75cd67-5797-4421-a09c-f962c8e4a64c%2Fblob)

1.Администратор переходит на страницу "Студенты". Список студентов пуст.

2.Администратор заполняет поля фильтра. В списке выводятся подходящие учетные записи.
Запрос для поиска записей [GET]:

http://www.web-test.ru/api/user/show?name=Жихарев&groupName=Исб-41&isActive=false&pageSize=5&page=1

3.По клику на интересующей записи отображается более подробная информация о студенте:
Фамилия, Имя, Отчество, Email, Группа и статус учётной записи.
Запрос для получения информации о студенте [GET]:

http://www.web-test.ru/api/user/getStudent/{STUDENT_ID}

4.Администратор нажимает кнопку "Редактировать"

5.Появляются элементы управления, показанные на скриншоте выше.
Если учетная запись уже подтверждена - статус учетной записи отображается как текст "Подтверждена". Если не подтверждена - предоставляется выбор варианта. По умолчанию выбран вариант "Подтвердить". 
[ ! ] В соответствии с этим при переходе к редактированию учетной записи, которая ещё не была подтверждена, свойство isActive автоматически проставляется в true. Если будет выбран вариант "Отклонить", учётная запись удаляется и список найденных записей обновляется.
Запрос для удаления учётной записи [POST]:

http://www.web-test.ru/api/user/delete/{id}

6.Администратор нажимает кнопку "Перевести". Отображается следующее диалоговое окно:

![uploads/53a9ad46-81bb-4e90-9104-c4c37c4f94a6/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F53a9ad46-81bb-4e90-9104-c4c37c4f94a6%2Fblob)

Запрос для получения списка групп [GET]:

http://www.web-test.ru/api/groups

Запрос для установки группы студента [POST]:

http://www.web-test.ru/api/student/setGroup

JSON: {"groupId" : 1, "userId" : 2 }

7.Администратор нажимает кнопку "Изменить пароль". Отображается диалоговое окно:

![uploads/847728a9-7b50-4b5f-8e66-8293f712c3da/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F847728a9-7b50-4b5f-8e66-8293f712c3da%2Fblob)

[ ! ] Предусмотреть валидацию пароля как при регистрации.

Запрос для установки пароля студенту [POST]:

http://www.web-test.ru/api/user/setPassword

JSON: {"userId" : 1, "password" : "qwerty123" }

8. Администратор нажимает кнопку "Сохранить"
Запрос для сохранения изменений [POST]:

http://www.web-test.ru/api/student/updateStudent

JSON: {"student":  { 
          "firstname" : "Вася",
          "patronymic" : "Петрович",
          "lastname" : "Пупкин",
          "email" : "vasya@mail.ru",
          "active" : true } }

**Comment by BikeInventor** [comment]
возможность преподавателю изменить пароль

**Comment by btshft** [comment]
Я скажу Жеке что ты умеешь писать ТЗ лучше чем Ходченков.

**Comment by BikeInventor** [comment]
Тогда, пожалуй, переделаю-ка я тут всё на мутные описания альтернативных вариантов.

**Comment by nyanjii** [comment]
ну а я в свою очередь сначала запилю по первому варианту, потом увижу второй, ничего не пойму сделаю как попало и буду ждать багов
