### ISSUE TITLE
Поиск по студентам - ошибка при вводе ФИО

### ISSUE THREAD

**Issue by BikeInventor** [KirillMaster/web-test#157]

**Comment by nyanjii** [comment]
Ничего не починилось.

**Comment by nyanjii** [comment]
При вводе в фильтр комбинации "Статус учетной записи" & рандомодичь (любое другое поле) возвращается ошибка: Too many parameters: the query defines 0 parameters and you bound 1
Ожидаемый результат: ошибок нет
