### ISSUE TITLE
[UI] Страница с учебными планами со списком учебных планов

### ISSUE THREAD

**Issue by karinarev** [KirillMaster/web-test#22]

**Comment by BikeInventor** [comment]
I. Реализовать "Учебные планы" как самостоятельную страницу, перейти на которую можно из главного меню. Пункт меню должен называться "ПЛАНЫ"
Поведение сайта при переходе на страницу:

а) Список учебных планов пуст, вверху страницы расположен фильтр по профилям в виде дропдауна;

б) Пользователь выбирает в дропдауне профиль, учебные планы которого его интересуют;

в) Отображается список учебных планов по заданному профилю (без пагинации, учебных планов не будет слишком много);

г) Пользователь кликает на интересующем его учебном плане;

д) Происходит переход на страницу со всеми планами дисциплин по конкретно выбранному плану (использовать url вида www.web-test.ru/studyplan/{id}, где {id} - идентификатор учебного плана);

е) На странице отображается список всех планов дисциплин с возможностью редактирования и удаления каждого из них (предусмотреть пагинацию и фильтрацию планов дисциплин по названию дисциплины);

ж) Также на странице имеется возможность переименования самого учебного плана (аналогию см. в темах, например: http://www.web-test.ru/admin/theme/1);

II. Предусмотреть переход на страницу конкретного плана со страницы "Главная". 
Сейчас на этой странице уже можно просмотреть список учебных планов по конкретному профилю, нужно будет только реализовать поведение, аналогичное пункту 1 д).
