### ISSUE TITLE
Страница результатов тестов

### ISSUE THREAD

**Issue by BikeInventor** [KirillMaster/web-test#59]
![uploads/2df5f019-2965-45e5-9430-248ca80effe5/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2df5f019-2965-45e5-9430-248ca80effe5%2Fblob)

Поведение системы при переходе на страницу: 
1. Выпадающие списки и таблица пуста
2. Пользователь выбирает направление из списка 
API-метод: http://www.web-test.ru/api/profiles
3. В список "Группы" подгружаются группы по направлению 
API-метод: http://www.web-test.ru/api/profile/{PROFILE_ID}/groups
4. Пользователь выбирает интересующую его группу
5. Выбор дисциплины и теста происходит аналогично п. 2-4:
API-методы: http://www.web-test.ru/api/disciplines
http://www.web-test.ru/api/disciplines/{DISCIPLINE_ID}/tests
6. В таблице отображаются ФИО студентов указанной группы, имеющих результаты тестирования по указанному тесту
API-метод: http://www.web-test.ru/api/results/show?groupId={GROUP_ID}&testId={TEST_ID}
7. Пользователь кликает по строке с интересующим его студентом
8. Происходит переход на страницу результата теста

**Comment by nyanjii** [comment]
Внесение изменений в мокап

![uploads/f1ec1060-4521-4729-ba32-f5f3055f935c/Выделение_043.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff1ec1060-4521-4729-ba32-f5f3055f935c%2F%D0%92%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_043.png)
